# Generated by Django 5.1.1 on 2024-11-09 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FluxoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ebit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ir", models.DecimalField(decimal_places=2, max_digits=10)),
                ("depreciacao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("receita_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("despesa_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fluxo_caixa_operacional",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
