# Generated by Django 5.1.1 on 2024-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_aposentadoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planejamentoaposentadoria',
            old_name='meta_renda_aposentadoria',
            new_name='meta_renda',
        ),
        migrations.RemoveField(
            model_name='planejamentoaposentadoria',
            name='economia_mensal',
        ),
        migrations.AddField(
            model_name='planejamentoaposentadoria',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
