# Generated by Django 5.1.1 on 2024-10-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educacao_financeira", "0003_remove_aula_youtube_id_aula_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aula",
            name="video",
        ),
        migrations.AddField(
            model_name="aula",
            name="video_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
