# Generated by Django 5.1.1 on 2024-11-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_gastos", "0002_metagasto"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiltroGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("roupa", "Roupa"),
                            ("eletronico", "Eletrônico"),
                            ("comida", "Comida"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle_gastos.gasto",
                    ),
                ),
            ],
        ),
    ]
