describe('test suite 1', () => {
    
    it('cenario1', () => {
        cy.visit('/');
        cy.get('[href="/login/"]').click()
        cy.get('#username').click()
        cy.get('#username').type('igor')
        cy.get('#password').type('123')
        cy.wait(1000)
        cy.get('button').click()
        cy.get('.menu-icon').click()
        cy.wait(2000)
        cy.get('[href="/controle_gastos/visualizar/"]').click()
        cy.wait(2000)
        cy.get('[href="/controle_gastos/add_meta/"]').click()
        cy.get('#valor_meta').click()
        cy.get('#valor_meta').type('100')
        cy.wait(2000)
        cy.get('button').click()
        cy.wait(2000)
        cy.get('.excluir').click()
        cy.wait(5000)
    })
    
    it('cenario2', () => {
        cy.visit('/');
        cy.get('[href="/login/"]').click()
        cy.get('#username').click()
        cy.get('#username').type('igor')
        cy.get('#password').type('123')
        cy.wait(1000)
        cy.get('button').click()
        cy.get('.menu-icon').click()
        cy.wait(2000)
        cy.get('[href="/controle_gastos/visualizar/"]').click()
        cy.wait(2000)
        cy.get('[href="/controle_gastos/add_meta/"]').click()
        cy.get('#valor_meta').click()
        cy.get('#valor_meta').type('100')
        cy.wait(2000)
        cy.get('button').click()
        cy.wait(2000)
        cy.get('[href="/controle_gastos/adicionar/"]').click()
        cy.get('#descricao').click()
        cy.get('#descricao').type('Iphone')
        cy.get('#valor').click()
        cy.get('#valor').type('20000')
        cy.get('#data').invoke('val', '2024-10-21').trigger('change')
        cy.get('button').click()
        cy.wait(5000)
        cy.get('.excluir').click()
        cy.wait(5000)
    })  
})