describe('test suite 1', () => {
    
    it('cenario1', () => {
        cy.visit('/');
        cy.get('[href="/login/"]').click()
        cy.get('#username').click()
        cy.get('#username').type('igor')
        cy.get('#password').type('123')
        cy.wait(1000)
        cy.get('button').click()
        cy.get('.menu-icon').click()
        cy.wait(2000)
        cy.get('[href="/imposto_renda/calculo/"]').click()
        cy.get('#nome').type('igor')
        cy.get('#renda_anual').type('250000')
        cy.wait(4000)
        cy.get('[type="submit"]').click()
        cy.wait(5000)
        cy.get('[href="/imposto_renda/historico/"]').click()
        cy.wait(4000)
    })
    it('cenario2', () => {
        cy.visit('/');
        cy.get('[href="/login/"]').click()
        cy.get('#username').click()
        cy.get('#username').type('igor')
        cy.get('#password').type('123')
        cy.get('button').click()
        cy.get('.menu-icon').click()
        cy.wait(2000)
        cy.get('[href="/imposto_renda/calculo/"]').click()
        cy.get('#nome').type('igor')
        cy.get('#renda_anual').type('50')
        cy.wait(4000)
        cy.get('[type="submit"]').click()
        cy.wait(5000)
        cy.get('[href="/imposto_renda/historico/"]').click()
        cy.wait(4000)
    })
})